# Generated by Django 5.2.5 on 2025-09-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="book_file",
            field=models.FileField(blank=True, null=True, upload_to="book_files/"),
        ),
    ]
