# Run: pre-commit clean && pre-commit install && pre-commit run --all-files
default_install_hook_types: [pre-commit]

# Global ignore to keep hooks fast
exclude: |
  (?x)^(
    node_modules/|
    media/|
    static/|
    .*/migrations/.*|
    .*\.min\.(js|css)$
  )

repos:
  # --- Python formatters / linters ---
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: [--max-line-length=120]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy

  # Security
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.6
    hooks:
      - id: bandit
        args: [--format=txt, --quiet]
        files: ^src/

  # Hygiene
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: requirements-txt-fixer
      - id: check-added-large-files
        args: [--maxkb=550]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3
          - prettier-plugin-tailwindcss@0.6.13
          - prettier-plugin-jinja-template@2.1.0
        files: >-
          \.(js|jsx|ts|tsx|css|scss|html|json|md|yml|yaml|svg|ico|txt)$

  # Local project hooks
  - repo: local
    hooks:
      - id: django-check
        name: django-check
        entry: bash -c 'python src/manage.py check --deploy'
        language: system
        types: [python]
        pass_filenames: false

  - repo: local
    hooks:
      - id: prospector
        name: prospector
        entry: prospector
        language: system
        types: [python]
        pass_filenames: false
        args:
          - --profile-path=.
          - --profile=.prospector.yaml
