name: Build & Push Docker image

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract branch name
        id: branch
        run: echo "name=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            GIT_BRANCH=${{ steps.branch.outputs.name }}
          tags: |
            pixiejitesh/bookstore-backend:${{ steps.branch.outputs.name }}
            pixiejitesh/bookstore-backend:latest
          cache-from: type=registry,ref=pixiejitesh/bookstore-backend:buildcache
          cache-to: type=registry,ref=pixiejitesh/bookstore-backend:buildcache,mode=max
